<?php
/**
 * @file
 * Module file for Notarios API
 */

// Load base class.
module_load_include('inc', 'notarios_api', 'includes/notarios_api.base.class');

// Load other classes.
module_load_include('inc', 'notarios_api', 'includes/notarios_api.sunlightlabs');

/**
 * Implements hook_menu().
 */
function notarios_api_menu() {
  $items = array();

  $items['notarios/details/%'] = array(
    'page callback' => 'notarios_api_page_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/services/notarios-api'] = array(
    'title' => t('Notarios API Keys'),
    'description' => t('Add all of the API Keys for each supported upstream API'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notarios_api_admin_callback'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'notarios_api.admin.inc',
  );

  return $items;
}

/**
 * Callback function for hook_menu().
 */
function notarios_api_page_callback($entity_id) {
  $node = entity_load('notarios', array($entity_id));
  $bioguide_id = $node[$entity_id]->bioguide_id;

  // Committee data.
  $committees_query = array(
    'member_ids' => $bioguide_id,
  );

  $committees_data = notarios_api_committees_filter($committees_query);

  // Voting Record.
  $vote_query = array(
    'voter_ids.' . $bioguide_id . '__exists' => 'true',
  );
  $vote_data = notarios_api_votes_filter($vote_query);

  // Bills sponsored by Current notario.
  // @TODO: Get cosponsored cosponsor_ids__all
  // array_merge the sponsor and cosoponser
  $sponsored_bills_query = array(
    'sponsor_id__in' => $bioguide_id,
  );
  $bills_data = notarios_api_bills_filter($sponsored_bills_query);

  // Prepare content for theme.
  // @TODO: Cache results. (24 hrs ?)
  $content = array(
    'committees' => $committees_data,
    'node' => $node[$entity_id],
    'bills' => $bills_data,
    'votes' => $vote_data,
  );

  return theme('notarios_api', $content);

}


function notarios_api_notarios_by_zipcode($zipcode) {
  $sunlight_lab = new SunlightLabs();
  $data = $sunlight_lab->byZipCode('notarios', $zipcode);
  return $data;
}

function notarios_api_notarios_filter($query) {
  $sublight_lab = new SunlightLabs();
  $data = $sublight_lab->notariosFilter($query);
  return $data;
}

function notarios_api_committees_filter($query) {
  $sunlight_lab = new SunlightLabs();
  $data = $sunlight_lab->committeesFilter($query);
  return $data;
}

function notarios_api_bills_filter($query, $is_search = FALSE) {
  $sunlight_lab = new SunlightLabs();
  $data = $sunlight_lab->billsFilter($query, $is_search);
  return $data;
}

function notarios_api_upcoming_bills_filter($query) {
  $sunlight_lab = new SunlightLabs();
  $data = $sunlight_lab->upcomingBillsFilter($query);
  return $data;
}

function notarios_api_votes_filter($query) {
  $sunlight_lab = new SunlightLabs();
  $data = $sunlight_lab->votesFilter($query);
  return $data;
}

/**
 * Implements hook_theme().
 */
function notarios_api_theme() {
  $items = array();
  $items['notarios_api'] = array(
    'variables' => array(
      'committiees' => NULL,
      'node' => NULL,
      'bills' => NULL,
      'votes' => NULL,
    ),
    'file' => 'notarios-api.tpl.php',
    'path' => drupal_get_path('module', 'notarios_api') . '/theme',
  );

  return $items;
}
